import os
import sys
import math
import warnings
from collections import OrderedDict
# sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
def _trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    # Values are generated by using a truncated uniform distribution and
    # then using the inverse CDF for the normal distribution.
    # Get upper and lower cdf values
    l = norm_cdf((a - mean) / std)
    u = norm_cdf((b - mean) / std)

    # Uniformly fill tensor with values from [l, u], then translate to
    # [2l-1, 2u-1].
    tensor.uniform_(2 * l - 1, 2 * u - 1)

    # Use inverse cdf transform for normal distribution to get truncated
    # standard normal
    tensor.erfinv_()

    # Transform to proper mean, std
    tensor.mul_(std * math.sqrt(2.))
    tensor.add_(mean)

    # Clamp to ensure it's in the proper range
    tensor.clamp_(min=a, max=b)
    return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
   
    with torch.no_grad():
        return _trunc_normal_(tensor, mean, std, a, b)
    
class MLPBlock(nn.Module):
    """
    Overview: 
        Basic 2 layer MLP block with GELU activation and dropout.
    Process
        [..., dim] -> [..., inter_dim] -> [..., dim] 
    """
    def __init__(self, dim, inter_dim, dropout_ratio):
        super().__init__()
        self.ff = nn.Sequential(
            nn.LayerNorm(dim), #! LN add 1
            nn.Linear(dim, inter_dim),
            nn.GELU(),
            nn.Dropout(dropout_ratio),
            nn.Linear(inter_dim, dim),
            nn.Dropout(dropout_ratio))
    def forward(self, x):
        return self.ff(x)
    
class MixerLayer(nn.Module):
    def __init__(self, hidden_dim, hidden_inter_dim, token_dim, token_inter_dim, dropout_ratio):
        super().__init__()

        self.layernorm1 = nn.LayerNorm(hidden_dim)
        self.MLP_token = MLPBlock(token_dim, token_inter_dim, dropout_ratio)

        self.layernorm2 = nn.LayerNorm(hidden_dim)
        self.MLP_channel = MLPBlock(hidden_dim, hidden_inter_dim, dropout_ratio)

        self.fusion_norm = nn.LayerNorm(hidden_dim) #! LN add 2

    def forward(self, x):
        y = self.layernorm1(x)     # [B, T, H]
        y = y.transpose(2, 1)      # [B, H, T]
        y = self.MLP_token(y)      # [B, H, T]
        y = y.transpose(2, 1)      # [B, T, H]
        z = self.layernorm2(x + y) # [B, T, H]
        z = self.MLP_channel(z)    # [B, T, H]
        out = x + y + z
        out = self.fusion_norm(out)
        return out

class VectorQuantizeTokenizer(nn.Module):

    def __init__(self, input_dim: int,
                    output_dim: int, 
                    #! encoder params
                    encoder_num_blocks: int, 
                    num_joints: int, 
                    encoder_token_inter_dim: int,
                    encoder_hidden_dim: int, 
                    encoder_hidden_inter_dim: int, 
                    encoder_dropout: float, 
                    #! codebook params
                    token_num: int,
                    token_class_num: int,
                    token_dim: int,
                    ema_decay: float,
                    #! decoder params
                    decoder_num_blocks: int,
                    decoder_hidden_dim: int, 
                    decoder_hidden_inter_dim: int, 
                    decoder_token_inter_dim: int, 
                    decoder_p_dropout: float,
                    stage: str = "tokenizer",  # "tokenizer" or "classifier",
                    use_intrinsic=False,   # 是否启用内参
                    intrinsic_dim=4,       # [fx, fy, cx, cy]
                    intrinsic_hidden_dim=128,
                    drop_rate=0.2
        ) -> None:
        super().__init__()
        #! input
        self.num_joints = num_joints
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.stage = stage

        #! Encoder part
        self.drop_rate = drop_rate
        self.encoder_num_blocks = encoder_num_blocks
        self.encoder_hidden_dim = encoder_hidden_dim
        self.encoder_hidden_inter_dim = encoder_hidden_inter_dim
        self.encoder_token_inter_dim = encoder_token_inter_dim
        self.encoder_dropout = encoder_dropout
        self.invisible_token = nn.Parameter(torch.zeros(1, 1, self.encoder_hidden_dim))
        trunc_normal_(self.invisible_token, mean=0., std=0.02, a=-0.02, b=0.02)

        self.start_embed = nn.Sequential(
            nn.Linear(self.input_dim, self.encoder_hidden_dim),
            nn.LayerNorm(self.encoder_hidden_dim) #! LN add 3
        )
        self.encoder = nn.ModuleList(
            [MixerLayer(self.encoder_hidden_dim, self.encoder_hidden_inter_dim, 
                self.num_joints, self.encoder_token_inter_dim,
                self.encoder_dropout) for _ in range(self.encoder_num_blocks)])
        #& input: [batch_size, num_joints, encoder_hidden_dim] in [B, K, H]
        self.encoder_layer_norm = nn.LayerNorm(self.encoder_hidden_dim)

        #! codebook part
        self.token_num = token_num
        self.token_class_num = token_class_num
        self.token_dim = token_dim
        self.token_mlp = nn.Linear(self.num_joints, self.token_num)
        self.feature_embed = nn.Linear(self.encoder_hidden_dim, self.token_dim)
        self.decay = ema_decay
        self.register_buffer('codebook', torch.empty(self.token_class_num, self.token_dim))
        self.codebook.data.normal_()
        self.register_buffer('ema_cluster_size', torch.zeros(self.token_class_num))
        self.register_buffer('ema_w', torch.empty(self.token_class_num, self.token_dim))
        self.ema_w.data.normal_() 

        #! Decoder part
        self.decoder_num_blocks = decoder_num_blocks
        self.decoder_hidden_dim = decoder_hidden_dim
        self.decoder_hidden_inter_dim = decoder_hidden_inter_dim
        self.decoder_token_inter_dim = decoder_token_inter_dim
        self.decoder_dropout = decoder_p_dropout

        self.decoder_token_mlp = nn.Sequential(
            nn.Linear(self.token_num, self.num_joints),
            nn.LayerNorm(self.num_joints) #! LN add 4
        )
        self.decoder_start = nn.Sequential(
            nn.Linear(self.token_dim, self.decoder_hidden_dim),
            nn.LayerNorm(self.decoder_hidden_dim) #! LN add 5
        )
        self.decoder = nn.ModuleList(
            [MixerLayer(self.decoder_hidden_dim, self.decoder_hidden_inter_dim,
                self.num_joints, self.decoder_token_inter_dim, 
                self.decoder_dropout) for _ in range(self.decoder_num_blocks)])
        self.decoder_layer_norm = nn.LayerNorm(self.decoder_hidden_dim)

        self.recover_embed = nn.Linear(self.decoder_hidden_dim, self.output_dim)

    def forward(self, x, cls_logits=None, train=True, **kwargs):
        """
        Forward pass of the VectorQuantizeTokenizer.
        Args:
            x (torch.Tensor): Input tensor of shape [B, num_joints, input_dim].
            cls_logits (torch.Tensor): Class logits for classifier stage, shape [B, token_num, token_class_num].
        Returns:
            torch.Tensor: Reconstructed output tensor of shape [B, num_joints, output_dim].
            torch.Tensor: Encoding indices (only in tokenizer stage).
            torch.Tensor: Codebook loss (only in tokenizer stage).
        """
        # intrinsic_matrix = kwargs.get("intrinsic_matrix", None)
        # rotation = kwargs.get("rotation", None)

        bs = x.shape[0]
        if train or self.stage == "tokenizer":
            # Encoder   
            encode_feat = self.start_embed(x)  # [B, num_joints, encoder_hidden_dim]

            #! 新增加 mask 部分！
            if train and self.stage == "tokenizer":
                random_mask_ind = torch.rand((bs, self.num_joints), device=x.device) > self.drop_rate

                mask_tokens = self.invisible_token.expand(bs, x.shape[1], -1)
                w = random_mask_ind.unsqueeze(-1).type_as(mask_tokens)
                encode_feat = w * encode_feat + (1 - w) * mask_tokens

            for layer in self.encoder:
                encode_feat = layer(encode_feat)
            encode_feat = self.encoder_layer_norm(encode_feat)
            # Tokenization
            encode_feat = encode_feat.transpose(2, 1)  # [B, encoder_hidden_dim, num_joints]
            encode_feat = self.token_mlp(encode_feat).transpose(2, 1)  # [B, encoder_hidden_dim, token_num]
            encode_feat = self.feature_embed(encode_feat).flatten(0, 1)  # [B, token_num, token_dim]


            distances = torch.sum(encode_feat**2, dim=1, keepdim=True) \
                        + torch.sum(self.codebook**2, dim=1) \
                        - 2 * torch.matmul(encode_feat, self.codebook.t())
            encoding_indices = torch.argmin(distances, dim=1)  # [B, token_num]
            encodings = torch.zeros(encoding_indices.shape[0], self.token_class_num, device=x.device)
            encodings.scatter_(1, encoding_indices.unsqueeze(1), 1)  # [B, token_num, token_class_num]
        
        else:
            encoding_indices = None

        if self.stage == "classifier":
            part_token_feat = torch.matmul(cls_logits, self.codebook)
        else:
            part_token_feat = torch.matmul(encodings, self.codebook)

        if train and self.stage == "tokenizer":
            # Update codebook using EMA (only in tokenizer stage)
            dw = torch.matmul(encodings.t(), encode_feat.detach())
            n_encodings, n_dw = encodings.numel(), dw.numel()
            encodings_shape, dw_shape = encodings.shape, dw.shape
            combined = torch.cat((encodings.flatten(), dw.flatten()))
            sync_combined = combined
            sync_encodings, sync_dw = torch.split(sync_combined, [n_encodings, n_dw])
            sync_encodings, sync_dw = sync_encodings.view(encodings_shape), sync_dw.view(dw_shape)
            
            self.ema_cluster_size = self.ema_cluster_size * self.decay + \
                                    (1 - self.decay) *  torch.sum(sync_encodings, 0)
            n = torch.sum(self.ema_cluster_size.data)
            self.ema_cluster_size = ((self.ema_cluster_size + 1e-5) / (n + self.token_class_num * 1e-5) * n)
            self.ema_w = self.ema_w * self.decay + (1 - self.decay) * sync_dw
            self.codebook = self.ema_w / self.ema_cluster_size.unsqueeze(1)
            e_latent_loss = F.mse_loss(part_token_feat.detach(), encode_feat) + F.mse_loss(part_token_feat, encode_feat.detach())
            part_token_feat = encode_feat + (part_token_feat - encode_feat).detach()
            
        else:
            e_latent_loss = None

        # Decoder
        part_token_feat = part_token_feat.view(bs, -1, self.token_dim)
        part_token_feat = part_token_feat.transpose(2, 1)  # [B, token_dim, token_num]
        part_token_feat = self.decoder_token_mlp(part_token_feat)  # [B, token_dim, num_joints]
        part_token_feat = part_token_feat.transpose(2, 1)  # [B, num_joints, token_dim]
        decode_feat = self.decoder_start(part_token_feat)  # [B, num_joints, decoder_hidden_dim]

        for layer in self.decoder:
            decode_feat = layer(decode_feat)
        decode_feat = self.decoder_layer_norm(decode_feat)

        # Recover output
        reconstruct = self.recover_embed(decode_feat)  # [B, num_joints, data_dim]
        return reconstruct, encoding_indices, e_latent_loss

    def init_weights(self, pretrained=""):
        """Initialize model weights."""

        parameters_names = set()
        for name, _ in self.named_parameters():
            parameters_names.add(name)

        buffers_names = set()
        for name, _ in self.named_buffers():
            buffers_names.add(name)

        if os.path.isfile(pretrained):
            print("Loading pretrained tokenizer....")
            assert (self.stage == "classifier"), "Training tokenizer does not need to load model"
            pretrained_state_dict = torch.load(pretrained, map_location=lambda storage, loc: storage)

            # need_init_state_dict = {}
            new_state_dict = OrderedDict()
            for k, v in pretrained_state_dict['model_state_dict'].items():
                name = k.replace("module.", "")  # 去掉 "module." 前缀
                new_state_dict[name] = v

            # for name, m in pretrained_state_dict['model_state_dict'].items():
            #     if (f"module.{name}" in parameters_names) or (f"module.{name}" in buffers_names):
            #         need_init_state_dict[name] = m
            self.load_state_dict(new_state_dict, strict=True)
            print(f"Tokenizer pretrain weight loaded successfully!")
        else:
            if self.stage == "classifier":
                print('If you are training a classifier, '\
                    'must check that the well-trained tokenizer '\
                    'is located in the correct path.')


if __name__ == "__main__":
    # Test with Batch_size=48, num_joints=7, dim=3
    batch_size = 48
    num_joints = 7
    dim = 3

    # Initialize the tokenizer
    tokenizer = VectorQuantizeTokenizer(
        input_dim=dim,
        output_dim=dim, 
        encoder_num_blocks=4,
        num_joints=num_joints,
        encoder_token_inter_dim=64,
        encoder_hidden_dim=128,
        encoder_hidden_inter_dim=32,
        encoder_dropout=0.1,
        token_num=10,
        token_class_num=20,
        token_dim=32,
        ema_decay=0.99,
        decoder_num_blocks=4,
        decoder_hidden_dim=128,
        decoder_hidden_inter_dim=32,
        decoder_token_inter_dim=64,
        decoder_p_dropout=0.1,
        stage="tokenizer"  # or "classifier"
    )

    # Create a random input tensor [48, 7, 3]
    input_tensor = torch.randn(batch_size, num_joints, dim)

    # Forward pass
    if tokenizer.stage == "tokenizer":
        output_tensor, encoding_indices, e_latent_loss = tokenizer(input_tensor)
        print("Tokenizer Output shape:", output_tensor.shape)  # [48, 7, 3]
        print("Encoding indices shape:", encoding_indices.shape)  # [48, 10]
        print("Codebook loss:", e_latent_loss)
    else:
        # Classifier stage: provide cls_logits
        cls_logits = torch.randn(batch_size, tokenizer.token_num, tokenizer.token_class_num)
        output_tensor, _, _ = tokenizer(input_tensor, cls_logits)
        print("Classifier Output shape:", output_tensor.shape)  # [48, 7, 3]
